cache:
  yarn: true
  directories:
    - $HOME/cache
    - $HOME/.m2
services:
  - mysql
  - postgresql
  - mongodb
matrix:
  include:
    - env: OPENRASP_LANG=php5 CC=gcc-4.9 CXX=g++-4.9 NO_INTERACTION=1 REPORT_EXIT_STATUS=1
      dist: trusty
      language: php
      php: 5.4
      sudo: true
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - gdb
            - g++-4.9
            - openssl
            - libssl-dev
            - libsslcommon2-dev
            - libcurl4-openssl-dev
            - libpcre3-dev
before_script:
  - bash ./travis/$OPENRASP_LANG/before_script.sh
script:
  - bash ./travis/$OPENRASP_LANG/script.sh

after_script:
  - bash ./travis/$OPENRASP_LANG/failure.sh

